[build]
command = "npm run build"
publish = ".vuepress/dist"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[plugins]]
  # runs Cypress tests against the deployed URL
  # https://github.com/cypress-io/netlify-plugin-cypress
  package = "netlify-plugin-cypress"
